services:
  mongodb:
    image: mongo:6.0.13
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.hello().ok"]
      interval: 5s
      start_period: 5s
      retries: 3
    ports:
      - "27017:27017"

  trade-imports-data-api-stub:
    image: defradigital/trade-imports-data-api-stub:${TRADE_IMPORTS_DATA_API_STUB:-latest}
    env_file:
      - ./config/defaults.env
      - ./config/trade-imports-data-api-stub.env
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8085/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "8085:8085"

  pha-import-notifications:
    image: defradigital/pha-import-notifications:${PHA_IMPORT_NOTIFICATIONS:-latest}
    env_file:
      - ./config/defaults.env
      - ./config/pha-import-notifications.env
    depends_on:
      mongodb:
        condition: service_healthy
      trade-imports-data-api-stub:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "8080:8080"
