services:
  floci:
    image: floci/floci:1.5.25-compat
    env_file:
      - ./config/aws.env
      - ./config/floci.env
    volumes:
      - ./scripts/floci:/etc/floci/init/ready.d
    ports:
      - "4566:4566"

  mongodb:
    image: mongo:6.0.28
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.hello().ok"]
      interval: 5s
      start_period: 5s
      retries: 3
    ports:
      - "27017:27017"

  json-server:
    build: ./docker/json-server
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    command: ["/data/db.json"]
    volumes:
      - ./docker/json-server/data:/data
    ports:
      - 3000:3000

  trade-imports-data-api-stub:
    image: defradigital/trade-imports-data-api-stub:${TRADE_IMPORTS_DATA_API_STUB:-latest}
    env_file:
      - ./config/trade-imports-data-api-stub.env
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8085/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "8085:8085"

  pha-import-notifications:
    image: defradigital/pha-import-notifications:${PHA_IMPORT_NOTIFICATIONS:-latest}
    env_file:
      - ./config/aws.env
      - ./config/pha-import-notifications.env
    depends_on:
      floci:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      json-server:
        condition: service_healthy
      trade-imports-data-api-stub:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 3s
      start_period: 2s
      retries: 3
    ports:
      - "8080:8080"
